
source 'https://github.com/CocoaPods/Specs.git'

target 'DroiFeedbackDemo' do
    
pod 'DroiFeedbackSDK'
pod 'DroiCoreSDK'
post_install do |installer|
    require './Pods/DroiCoreSDK/scripts/postInstall.rb'
    DroiCoreParser.installParser()
end
pod 'SDWebImage'
pod 'MBProgressHUD'
end